export default [{
    id: 1,
    categoryName: 'Lotstring',
    slug: 'instagram.com',
    categoryParent: 'Afrikaans',
  },
  {
    id: 2,
    categoryName: 'Home Ing',
    slug: 'shareasale.com',
    categoryParent: 'Burmese',
  },
  {
    id: 3,
    categoryName: 'Asoka',
    slug: 'microsoft.com',
    categoryParent: 'Finnish',
  },
  {
    id: 4,
    categoryName: 'Regrant',
    slug: 'netvibes.com',
    categoryParent: 'Macedonian',
  },
  {
    id: 5,
    categoryName: 'Transcof',
    slug: 'ask.com',
    categoryParent: 'Gagauz',
  },
  {
    id: 6,
    categoryName: 'Lotstring',
    slug: 'ucoz.ru',
    categoryParent: 'Kurdish',
  },
  {
    id: 7,
    categoryName: 'Keylex',
    slug: 'google.cn',
    categoryParent: 'Ndebele',
  },
  {
    id: 8,
    categoryName: 'Voltsillam',
    slug: 'privacy.gov.au',
    categoryParent: 'Hindi',
  },
  {
    id: 9,
    categoryName: 'Tempsoft',
    slug: 'businessinsider.com',
    categoryParent: 'Dhivehi',
  },
  {
    id: 10,
    categoryName: 'Mat Lam Tam',
    slug: 'trellian.com',
    categoryParent: 'Sotho',
  },
  {
    id: 11,
    categoryName: 'Gembucket',
    slug: 'ucoz.ru',
    categoryParent: 'Zulu',
  },
  {
    id: 12,
    categoryName: 'Duobam',
    slug: 'who.int',
    categoryParent: 'Amharic',
  },
  {
    id: 13,
    categoryName: 'Aerified',
    slug: 'princeton.edu',
    categoryParent: 'Nepali',
  },
  {
    id: 14,
    categoryName: 'Trippledex',
    slug: 'over-blog.com',
    categoryParent: 'Tok Pisin',
  },
  {
    id: 15,
    categoryName: 'Zamit',
    slug: 'angelfire.com',
    categoryParent: 'Filipino',
  },
  {
    id: 16,
    categoryName: 'Transcof',
    slug: 'patch.com',
    categoryParent: 'Tetum',
  },
  {
    id: 17,
    categoryName: 'Flowdesk',
    slug: 'mapy.cz',
    categoryParent: 'Dhivehi',
  },
  {
    id: 18,
    categoryName: 'Trippledex',
    slug: 'wired.com',
    categoryParent: 'Amharic',
  },
  {
    id: 19,
    categoryName: 'Mat Lam Tam',
    slug: 'instagram.com',
    categoryParent: 'Albanian',
  },
  {
    id: 20,
    categoryName: 'Bitchip',
    slug: 'cyberchimps.com',
    categoryParent: 'Haitian Creole',
  },
  {
    id: 21,
    categoryName: 'Span',
    slug: 'howstuffworks.com',
    categoryParent: 'Bulgarian',
  },
  {
    id: 22,
    categoryName: 'Opela',
    slug: 'trellian.com',
    categoryParent: 'Armenian',
  },
  {
    id: 23,
    categoryName: 'Voltsillam',
    slug: 'ftc.gov',
    categoryParent: 'Dzongkha',
  },
  {
    id: 24,
    categoryName: 'Voyatouch',
    slug: 'netlog.com',
    categoryParent: 'Kannada',
  },
  {
    id: 25,
    categoryName: 'Prodder',
    slug: 'myspace.com',
    categoryParent: 'Kannada',
  },
  {
    id: 26,
    categoryName: 'Cardguard',
    slug: 'i2i.jp',
    categoryParent: 'Norwegian',
  },
  {
    id: 27,
    categoryName: 'Opela',
    slug: 'usnews.com',
    categoryParent: 'Amharic',
  },
  {
    id: 28,
    categoryName: 'Asoka',
    slug: 'mozilla.com',
    categoryParent: 'Kashmiri',
  },
  {
    id: 29,
    categoryName: 'Toughjoyfax',
    slug: 'techcrunch.com',
    categoryParent: 'Bosnian',
  },
  {
    id: 30,
    categoryName: 'Span',
    slug: 'github.com',
    categoryParent: 'Estonian',
  },
  {
    id: 31,
    categoryName: 'Job',
    slug: 'census.gov',
    categoryParent: 'Lao',
  },
  {
    id: 32,
    categoryName: 'Stim',
    slug: 'addtoany.com',
    categoryParent: 'Estonian',
  },
  {
    id: 33,
    categoryName: 'Overhold',
    slug: 'ning.com',
    categoryParent: 'Tetum',
  },
  {
    id: 34,
    categoryName: 'Konklab',
    slug: 'amazon.co.uk',
    categoryParent: 'Guaraní',
  },
];