export default [{
  id: 1,
  categoryName: "Shindo",
  slug: "/yhwxmlif"
}, {
  id: 2,
  categoryName: "Fabaceae",
  slug: "/apgxtozg"
}, {
  id: 3,
  categoryName: "Polygonaceae",
  slug: "/wipzvcmm"
}, {
  id: 4,
  categoryName: "Bacidiaceae",
  slug: "/eoxmvkma"
}, {
  id: 5,
  categoryName: "Liliaceae",
  slug: "/cdjzbggg"
}, {
  id: 6,
  categoryName: "Asteraceae",
  slug: "/lizppkpt"
}, {
  id: 7,
  categoryName: "Pinaceae",
  slug: "/hczjwqdn"
}, {
  id: 8,
  categoryName: "Lichinaceae",
  slug: "/fizwpiac"
}, {
  id: 9,
  categoryName: "Apiaceae",
  slug: "/kgypoxrp"
}, {
  id: 10,
  categoryName: "Fabaceae",
  slug: "/gngvnmkt"
}, {
  id: 11,
  categoryName: "Araceae",
  slug: "/xkjqknlu"
}, {
  id: 12,
  categoryName: "Rubiaceae",
  slug: "/qsaouxzj"
}, {
  id: 13,
  categoryName: "Asteraceae",
  slug: "/vlypckuq"
}, {
  id: 14,
  categoryName: "Physciaceae",
  slug: "/gcnduvls"
}, {
  id: 15,
  categoryName: "Goodeniaceae",
  slug: "/qyyqpjws"
}, {
  id: 16,
  categoryName: "Burseraceae",
  slug: "/hqjrqfnc"
}, {
  id: 17,
  categoryName: "Hydrophyllaceae",
  slug: "/bqghnxtf"
}, {
  id: 18,
  categoryName: "Solanaceae",
  slug: "/wekfgzlj"
}, {
  id: 19,
  categoryName: "Scrophulariaceae",
  slug: "/ulajtdiy"
}, {
  id: 20,
  categoryName: "Lentibulariaceae",
  slug: "/tbgfamtp"
}, {
  id: 21,
  categoryName: "Bruchiaceae",
  slug: "/rhmxrrpw"
}, {
  id: 22,
  categoryName: "Fabaceae",
  slug: "/jcuydgra"
}, {
  id: 23,
  categoryName: "Notothyladaceae",
  slug: "/ukvmjddd"
}, {
  id: 24,
  categoryName: "Celastraceae",
  slug: "/fwyefufi"
}, {
  id: 25,
  categoryName: "Arthoniaceae",
  slug: "/ckmvymsh"
}, {
  id: 26,
  categoryName: "Gesneriaceae",
  slug: "/qnnhixfi"
}, {
  id: 27,
  categoryName: "Poaceae",
  slug: "/wcjglsxy"
}, {
  id: 28,
  categoryName: "Caryophyllaceae",
  slug: "/pnsttfcv"
}, {
  id: 29,
  categoryName: "Asteraceae",
  slug: "/jwiobxmm"
}, {
  id: 30,
  categoryName: "Trichotheliaceae",
  slug: "/cilqstom"
}, {
  id: 31,
  categoryName: "Onagraceae",
  slug: "/qaapnyrj"
}, {
  id: 32,
  categoryName: "Myrsinaceae",
  slug: "/ukrfppbv"
}, {
  id: 33,
  categoryName: "Bryaceae",
  slug: "/lylxvqdl"
}, {
  id: 34,
  categoryName: "Ericaceae",
  slug: "/giwilyow"
}]