export default [{
  id: 1,
  tagName: "Scrophulariaceae",
  slug: "/yhwxmlif"
}, {
  id: 2,
  tagName: "Fabaceae",
  slug: "/apgxtozg"
}, {
  id: 3,
  tagName: "Polygonaceae",
  slug: "/wipzvcmm"
}, {
  id: 4,
  tagName: "Bacidiaceae",
  slug: "/eoxmvkma"
}, {
  id: 5,
  tagName: "Liliaceae",
  slug: "/cdjzbggg"
}, {
  id: 6,
  tagName: "Asteraceae",
  slug: "/lizppkpt"
}, {
  id: 7,
  tagName: "Pinaceae",
  slug: "/hczjwqdn"
}, {
  id: 8,
  tagName: "Lichinaceae",
  slug: "/fizwpiac"
}, {
  id: 9,
  tagName: "Apiaceae",
  slug: "/kgypoxrp"
}, {
  id: 10,
  tagName: "Fabaceae",
  slug: "/gngvnmkt"
}, {
  id: 11,
  tagName: "Araceae",
  slug: "/xkjqknlu"
}, {
  id: 12,
  tagName: "Rubiaceae",
  slug: "/qsaouxzj"
}, {
  id: 13,
  tagName: "Asteraceae",
  slug: "/vlypckuq"
}, {
  id: 14,
  tagName: "Physciaceae",
  slug: "/gcnduvls"
}, {
  id: 15,
  tagName: "Goodeniaceae",
  slug: "/qyyqpjws"
}, {
  id: 16,
  tagName: "Burseraceae",
  slug: "/hqjrqfnc"
}, {
  id: 17,
  tagName: "Hydrophyllaceae",
  slug: "/bqghnxtf"
}, {
  id: 18,
  tagName: "Solanaceae",
  slug: "/wekfgzlj"
}, {
  id: 19,
  tagName: "Scrophulariaceae",
  slug: "/ulajtdiy"
}, {
  id: 20,
  tagName: "Lentibulariaceae",
  slug: "/tbgfamtp"
}, {
  id: 21,
  tagName: "Bruchiaceae",
  slug: "/rhmxrrpw"
}, {
  id: 22,
  tagName: "Fabaceae",
  slug: "/jcuydgra"
}, {
  id: 23,
  tagName: "Notothyladaceae",
  slug: "/ukvmjddd"
}, {
  id: 24,
  tagName: "Celastraceae",
  slug: "/fwyefufi"
}, {
  id: 25,
  tagName: "Arthoniaceae",
  slug: "/ckmvymsh"
}, {
  id: 26,
  tagName: "Gesneriaceae",
  slug: "/qnnhixfi"
}, {
  id: 27,
  tagName: "Poaceae",
  slug: "/wcjglsxy"
}, {
  id: 28,
  tagName: "Caryophyllaceae",
  slug: "/pnsttfcv"
}, {
  id: 29,
  tagName: "Asteraceae",
  slug: "/jwiobxmm"
}, {
  id: 30,
  tagName: "Trichotheliaceae",
  slug: "/cilqstom"
}, {
  id: 31,
  tagName: "Onagraceae",
  slug: "/qaapnyrj"
}, {
  id: 32,
  tagName: "Myrsinaceae",
  slug: "/ukrfppbv"
}, {
  id: 33,
  tagName: "Bryaceae",
  slug: "/lylxvqdl"
}, {
  id: 34,
  tagName: "Ericaceae",
  slug: "/giwilyow"
}]